title: Nahian Haque
theme: jekyll-theme-minimal
subtitle: B.A. Economics & Data Science Minor | Stanford 2025
logo: /assets/img/headshot_circle.png
email: nahian@stanford.edu
linkedin: www.linkedin.com/in/nahianhaque25
